=== AntonioG70/PRI2020/TP2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT projectRecord (info, workteam, abstract, deliverables, data)+ >
<!ELEMENT info (titulo, subtitulo?, beginD, endD, supervisor) >

<!ATTLIST info 
    key_name ID #REQUIRED
    >
    
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT subtitulo (#PCDATA) >
<!ELEMENT beginD (#PCDATA) >
<!ELEMENT endD (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >

<!ATTLIST  supervisor
    nomelink CDATA  #REQUIRED
    >

<!ELEMENT workteam (person)+ >
<!ELEMENT person (nome) >
<!ELEMENT nome (#PCDATA) >

<!ATTLIST person
    numero ID #REQUIRED
    linkEmail CDATA #REQUIRED
    >
    
<!ELEMENT abstract (paragrafo)+ >
<!ELEMENT paragrafo (text, bolds, italico, links)+  >
<!ELEMENT text (#PCDATA) >
<!ELEMENT bolds (#PCDATA) >
<!ELEMENT italico (#PCDATA) >
<!ELEMENT links (#PCDATA) >

<!ATTLIST links 
    url CDATA #REQUIRED
    >
    
<!ELEMENT deliverables (linkFile)+ >
<!ELEMENT linkFile (#PCDATA) >

<!ATTLIST linkFile 
    fileUrl CDATA #REQUIRED
    >

<!ELEMENT data (#PCDATA) >

=== AntonioG70/PRI2020/TP2/TP2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectRecord SYSTEM "file:/C:/Users/anton/OneDrive/Ambiente%20de%20Trabalho/PR.dtd">
<projectRecord>
    <info key_name="A85813_PRI_TP2">
        <titulo>TP2</titulo>
        <subtitulo>PRI</subtitulo>
        <beginD>22 de Outubro 2020</beginD>
        <endD>22 de Outubro 2020</endD>
        <supervisor nomelink="www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
    </info>
    <workteam>
        <person numero="A85813" linkEmail="a85813@alunos.uminho.pt">
            <nome>António Alexandre Carvalho Lindo</nome>
        </person>
    </workteam>
    <abstract>
        <paragrafo>
            <text>Trabalho 2 da UC de PRI, onde foi feito um modelo DTD de um Project Record, a respeitar uma lista de requisitos e
            gerado o respetivo XML.</text>
            <bolds></bolds>
            <italico></italico>
            <links url=""></links>
        </paragrafo>
    </abstract>
    <deliverables>
        <linkFile fileUrl="https://github.com/AntonioG70/PRI2020"></linkFile>
    </deliverables>
    <data>22 de Outubro de 2020</data>
</projectRecord>

=== AntonioG70/PRI2020/TP3/TP3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectRecord SYSTEM "file:/C:/Users/anton/OneDrive/Ambiente%20de%20Trabalho/Universidade/PLC/PRI/TP2/PR.dtd">
<projectRecord>
    <info key_name="A85813_PRI_TP3">
        <titulo>TP3</titulo>
        <subtitulo>PRI 2020</subtitulo>
        <beginD>29 de Outubro de 2020</beginD>
        <endD>31 de Outubro de 2020</endD>
        <supervisor nomelink="www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
    </info>
    <workteam>
        <person numero="A85813" linkEmail="mailto:a85813@alunos.uminho.pt">
            <nome>António Alexandre Carvalho Lindo</nome>
        </person>
    </workteam>
    <abstract>
        <paragrafo>
            <text>
                Neste TP3, foi feito um DTD a partir da arquitetura de um dado ficheiro XML.
                Posteriormente, foi feito um documento XSL, que criasse um website com os vários
                geossitios presentes no mesmo ficheiro XML dado. O website tem um indice com os varios sitios
                e uma pagina para cada um deles.
            </text>
        </paragrafo>
    </abstract>
    <deliverables>
        <linkFile fileUrl="https://github.com/AntonioG70/PRI2020/tree/main/TP3"></linkFile>
    </deliverables>
    <data>31 de Outubro de 2020</data>
</projectRecord>
